POST {{$dotenv BASE_URL}}/scan
Authorization: Beearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDMzMmNjZWRhODBiODljYWYzZDRmNDUiLCJ1c2VybmFtZSI6Imhvd2FyZCIsImlhdCI6MTY4MTI5NDc2NiwiZXhwIjoxNjg5MDcwNzY2fQ.-VxTcdcBZAqKRueK8uZSegOZOzU3fCTzygZ7NpU-JjY
Content-Type: application/json

{
    "url": "https://nepal.gov.np/"
}

### 

GET {{$dotenv BASE_URL}}/scan/6437030783a4bcf1304bbd92
Authorization: Beearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDMzMmNjZWRhODBiODljYWYzZDRmNDUiLCJ1c2VybmFtZSI6Imhvd2FyZCIsImlhdCI6MTY4MTI5NDc2NiwiZXhwIjoxNjg5MDcwNzY2fQ.-VxTcdcBZAqKRueK8uZSegOZOzU3fCTzygZ7NpU-JjY
