GET http://localhost:9999/setting
Authorization: Beearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDMzMmNjZWRhODBiODljYWYzZDRmNDUiLCJ1c2VybmFtZSI6Imhvd2FyZCIsImlhdCI6MTY4MTI5NDc2NiwiZXhwIjoxNjg5MDcwNzY2fQ.-VxTcdcBZAqKRueK8uZSegOZOzU3fCTzygZ7NpU-JjY

